import { account, appwriteConfig, databases, ID, isDemoMode, Query } from '../lib/appwrite';
import type { Follow, HelpOffer, OfferType, Profile, StepStatus, StepType, User, Visibility, Wish, WishBundle, WishStatus, WishStep, WishUpdate } from '../types/domain';

type Row = Record<string, unknown> & { $id: string; $createdAt?: string; $updatedAt?: string };
const now = () => new Date().toISOString();
const slugify = (s: string) => `${s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '').slice(0, 48)}-${Math.random().toString(36).slice(2, 6)}`;
const images = ['https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80','https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=1200&q=80','https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=1200&q=80','https://images.unsplash.com/photo-1523906834658-6e24ef2386f9?auto=format&fit=crop&w=1200&q=80','https://images.unsplash.com/photo-1528164344705-47542687000d?auto=format&fit=crop&w=1200&q=80','https://images.unsplash.com/photo-1518005020951-eccb494ad742?auto=format&fit=crop&w=1200&q=80'];

const seedWishes = ['Cross the Atlantic with my children','Find the person I want to build a life with','Open a tiny jazz café','Take my mother to see Rome','Walk across Japan','Write and publish my first graphic novel'].map((title, i): Wish => ({ id: `wish-${i+1}`, ownerId: i < 2 ? 'demo-user' : `seed-${i}`, ownerName: ['Mara','Thomas','Nina','Ari','Keiko','Jonas'][i], title, slug: slugify(title), description: ['A slow sea crossing with enough preparation that the children remember wonder, not fear.','I want to meet someone with whom ordinary days can become a home.','Twelve seats, late records, good coffee by day and two sets at night.','She has spoken about Rome for thirty years. I want to make it simple and beautiful.','A long walk through changing weather, small inns, and conversations I cannot plan.','A hand-drawn story about a city that keeps changing its name.'][i], imageUrl: images[i], visibility: i === 0 ? 'link' : 'public', status: ['exploring','dreaming','in_progress','exploring','dreaming','in_progress'][i] as WishStatus, location: ['Lisbon','Brighton','New Orleans','Rome','Japan','Rotterdam'][i], acceptsHelp: true, createdAt: now(), updatedAt: now() }));
let demo = { user: { id: 'demo-user', email: 'demo@wishlist.local', name: 'Mara' } as User | null, profiles: [{ id:'demo-user', userId:'demo-user', displayName:'Mara', location:'Porto', bio:'Collecting practical courage and good maps.', offersText:'I can offer route research, calm planning, photography, and introductions around coastal Portugal.', offerTags:['time','contacts','experience'], contactEmail:'mara@example.com', createdAt:now(), updatedAt:now() }] as Profile[], wishes: seedWishes, steps: [] as WishStep[], updates: [] as WishUpdate[], offers: [] as HelpOffer[], follows: [{ id:'follow-1', wishId:'wish-3', userId:'demo-user', createdAt:now() }] as Follow[] };
seedWishes.forEach((w, wi) => { ['Name the real first move','Find one person who has done it','Make the smallest test public'].forEach((t, i) => demo.steps.push({ id:`step-${wi}-${i}`, wishId:w.id, ownerId:w.ownerId, title:t, description:i===1?'Ask for one generous conversation.':'', position:i+1, status:i===0?'completed':i===1?'active':'planned', stepType:i===2?'test':'action', createdAt:now(), updatedAt:now() })); demo.updates.push({ id:`up-${wi}`, wishId:w.id, actorId:w.ownerId, actorName:w.ownerName, eventType:'wish_created', message:`${w.ownerName} opened this wish and started shaping the path.`, createdAt:now() }); });
const save = () => localStorage.setItem('wishlist-demo', JSON.stringify(demo)); const load = () => { const raw = localStorage.getItem('wishlist-demo'); if (raw) demo = JSON.parse(raw); }; if (typeof localStorage !== 'undefined') load();
const wishFrom = (r: Row): Wish => ({ id:r.$id, ownerId:String(r.owner_id), ownerName:String(r.owner_name), title:String(r.title), slug:String(r.slug), description:String(r.description), imageUrl:r.image_url as string, visibility:r.visibility as Visibility, status:r.status as WishStatus, location:r.location as string, targetDate:r.target_date as string, acceptsHelp:Boolean(r.accepts_help), createdAt:String(r.created_at || r.$createdAt), updatedAt:String(r.updated_at || r.$updatedAt) });
const stepFrom = (r: Row): WishStep => ({ id:r.$id, wishId:String(r.wish_id), ownerId:String(r.owner_id), title:String(r.title), description:r.description as string, position:Number(r.position), status:r.status as StepStatus, stepType:r.step_type as StepType, targetDate:r.target_date as string, createdAt:String(r.created_at || r.$createdAt), updatedAt:String(r.updated_at || r.$updatedAt) });
const profileFrom = (r: Row): Profile => ({ id:r.$id, userId:String(r.user_id), displayName:String(r.display_name), avatarUrl:r.avatar_url as string, location:r.location as string, bio:r.bio as string, offersText:r.offers_text as string, offerTags:(r.offer_tags as string[]) || [], contactEmail:r.contact_email as string, contactWhatsapp:r.contact_whatsapp as string, contactUrl:r.contact_url as string, createdAt:String(r.created_at || r.$createdAt), updatedAt:String(r.updated_at || r.$updatedAt) });
const updateFrom = (r: Row): WishUpdate => ({ id:r.$id, wishId:String(r.wish_id), actorId:String(r.actor_id), actorName:String(r.actor_name), eventType:String(r.event_type), message:String(r.message), createdAt:String(r.created_at || r.$createdAt) });
const offerFrom = (r: Row): HelpOffer => ({ id:r.$id, wishId:String(r.wish_id), stepId:r.step_id as string, wishOwnerId:String(r.wish_owner_id), helperId:String(r.helper_id), helperName:String(r.helper_name), offerType:r.offer_type as OfferType, message:String(r.message), contactUrl:r.contact_url as string, status:String(r.status) as HelpOffer['status'], createdAt:String(r.created_at || r.$createdAt), updatedAt:String(r.updated_at || r.$updatedAt) });
const followFrom = (r: Row): Follow => ({ id:r.$id, wishId:String(r.wish_id), userId:String(r.user_id), createdAt:String(r.created_at || r.$createdAt) });
async function createUpdate(wish: Wish, actor: User | null, eventType: string, message: string) { const u = { id: actor?.id || wish.ownerId, name: actor?.name || wish.ownerName }; if (isDemoMode) { demo.updates.unshift({ id:crypto.randomUUID(), wishId:wish.id, actorId:u.id, actorName:u.name, eventType, message, createdAt:now() }); save(); return; } await databases.createDocument(appwriteConfig.databaseId, appwriteConfig.updatesTableId, ID.unique(), { wish_id:wish.id, actor_id:u.id, actor_name:u.name, event_type:eventType, message, created_at:now() }); }
export const api = {
  demoMode: isDemoMode,
  async currentUser() { if (isDemoMode) return demo.user; try { const u = await account.get(); return { id:u.$id, email:u.email, name:u.name || u.email.split('@')[0] }; } catch { return null; } },
  async signIn(email:string,password:string){ if(isDemoMode){ demo.user={id:'demo-user',email,name:'Mara'}; save(); return demo.user;} await account.createEmailPasswordSession(email,password); return this.currentUser(); },
  async signUp(email:string,password:string,name:string){ if(isDemoMode){ demo.user={id:'demo-user',email,name:name||'Mara'}; save(); return demo.user;} const u=await account.create(ID.unique(),email,password,name); await account.createEmailPasswordSession(email,password); return {id:u.$id,email:u.email,name:u.name}; },
  async signOut(){ if(isDemoMode){ demo.user=null; save(); return;} await account.deleteSession('current'); },
  async profile(userId:string){ if(isDemoMode) return demo.profiles.find(p=>p.userId===userId); const d=await databases.getDocument(appwriteConfig.databaseId, appwriteConfig.profilesTableId, userId); return profileFrom(d as Row); },
  async saveProfile(p: Partial<Profile>, user: User){ const payload={ user_id:user.id, display_name:p.displayName || user.name, avatar_url:p.avatarUrl, location:p.location, bio:p.bio, offers_text:p.offersText, offer_tags:p.offerTags || [], contact_email:p.contactEmail, contact_whatsapp:p.contactWhatsapp, contact_url:p.contactUrl, created_at:p.createdAt || now(), updated_at:now() }; if(isDemoMode){ const ex=demo.profiles.find(x=>x.userId===user.id); const next={...(ex||{id:user.id,userId:user.id,createdAt:now(),offerTags:[]}),...p,displayName:p.displayName||user.name,updatedAt:now()} as Profile; demo.profiles=demo.profiles.filter(x=>x.userId!==user.id).concat(next); save(); return next;} const doc=await databases.createDocument(appwriteConfig.databaseId, appwriteConfig.profilesTableId, user.id, payload).catch(()=>databases.updateDocument(appwriteConfig.databaseId, appwriteConfig.profilesTableId, user.id, payload)); return profileFrom(doc as Row); },
  async listExplore(filter='New'){ if(isDemoMode) return demo.wishes.filter(w=>w.visibility==='public' && (filter==='Active'?w.status==='in_progress':filter==='Achieved'?w.status==='achieved':true)).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)); const qs=[Query.equal('visibility','public'), Query.orderDesc('updated_at'), Query.limit(50)]; if(filter==='Active') qs.unshift(Query.equal('status','in_progress')); if(filter==='Achieved') qs.unshift(Query.equal('status','achieved')); const d=await databases.listDocuments(appwriteConfig.databaseId, appwriteConfig.wishesTableId, qs); return d.documents.map(x=>wishFrom(x as Row)); },
  async myWishes(userId:string){ if(isDemoMode) return demo.wishes.filter(w=>w.ownerId===userId); const d=await databases.listDocuments(appwriteConfig.databaseId, appwriteConfig.wishesTableId,[Query.equal('owner_id',userId),Query.orderDesc('updated_at')]); return d.documents.map(x=>wishFrom(x as Row)); },
  async bundle(slug:string){ let wish:Wish; if(isDemoMode){ wish=demo.wishes.find(w=>w.slug===slug || w.id===slug)!; return { wish, steps:demo.steps.filter(s=>s.wishId===wish.id).sort((a,b)=>a.position-b.position), updates:demo.updates.filter(u=>u.wishId===wish.id), offers:demo.offers.filter(o=>o.wishId===wish.id), follows:demo.follows.filter(f=>f.wishId===wish.id), owner:demo.profiles.find(p=>p.userId===wish.ownerId) }; } const wd=await databases.listDocuments(appwriteConfig.databaseId, appwriteConfig.wishesTableId,[Query.equal('slug',slug),Query.limit(1)]); wish=wishFrom(wd.documents[0] as Row); const [sd,ud,od,fd]=await Promise.all([databases.listDocuments(appwriteConfig.databaseId,appwriteConfig.stepsTableId,[Query.equal('wish_id',wish.id),Query.orderAsc('position')]),databases.listDocuments(appwriteConfig.databaseId,appwriteConfig.updatesTableId,[Query.equal('wish_id',wish.id),Query.orderDesc('created_at')]),databases.listDocuments(appwriteConfig.databaseId,appwriteConfig.helpTableId,[Query.equal('wish_id',wish.id),Query.orderDesc('created_at')]),databases.listDocuments(appwriteConfig.databaseId,appwriteConfig.followsTableId,[Query.equal('wish_id',wish.id)])]); return { wish, steps:sd.documents.map(x=>stepFrom(x as Row)), updates:ud.documents.map(x=>updateFrom(x as Row)), offers:od.documents.map(x=>offerFrom(x as Row)), follows:fd.documents.map(x=>followFrom(x as Row)) } as WishBundle; },
  async saveWish(input: Partial<Wish>, steps: Partial<WishStep>[], user: User){ const t=now(); let wish:Wish; if(isDemoMode){ wish={ id:input.id||crypto.randomUUID(), ownerId:user.id, ownerName:user.name, title:input.title!, slug:input.slug||slugify(input.title!), description:input.description!, imageUrl:input.imageUrl, visibility:input.visibility||'private', status:input.status||'dreaming', location:input.location, targetDate:input.targetDate, acceptsHelp:input.acceptsHelp??true, createdAt:input.createdAt||t, updatedAt:t }; demo.wishes=demo.wishes.filter(w=>w.id!==wish.id).concat(wish); demo.steps=demo.steps.filter(s=>s.wishId!==wish.id).concat(steps.map((s,i)=>({ id:s.id||crypto.randomUUID(), wishId:wish.id, ownerId:user.id, title:s.title||`Step ${i+1}`, description:s.description, position:i+1, status:s.status||'planned', stepType:s.stepType||'action', createdAt:s.createdAt||t, updatedAt:t }))); await createUpdate(wish,user,input.id?'status_changed':'wish_created',input.id?'The wish was edited.':'The wish was created.'); save(); return wish; } const payload={ owner_id:user.id, owner_name:user.name, title:input.title, slug:input.slug||slugify(input.title!), description:input.description, image_url:input.imageUrl, visibility:input.visibility, status:input.status, location:input.location, target_date:input.targetDate, accepts_help:input.acceptsHelp, created_at:input.createdAt||t, updated_at:t }; const doc=input.id? await databases.updateDocument(appwriteConfig.databaseId,appwriteConfig.wishesTableId,input.id,payload) : await databases.createDocument(appwriteConfig.databaseId,appwriteConfig.wishesTableId,ID.unique(),payload); wish=wishFrom(doc as Row); for (const [i,s] of steps.entries()) { const sp={ wish_id:wish.id, owner_id:user.id, title:s.title, description:s.description, position:i+1, status:s.status||'planned', step_type:s.stepType||'action', target_date:s.targetDate, created_at:s.createdAt||t, updated_at:t }; if(s.id) await databases.updateDocument(appwriteConfig.databaseId,appwriteConfig.stepsTableId,s.id,sp); else await databases.createDocument(appwriteConfig.databaseId,appwriteConfig.stepsTableId,ID.unique(),sp); } await createUpdate(wish,user,input.id?'status_changed':'wish_created',input.id?'The wish was edited.':'The wish was created.'); return wish; },
  async follow(wish:Wish,user:User){ if(isDemoMode){ const ex=demo.follows.find(f=>f.wishId===wish.id&&f.userId===user.id); demo.follows=ex?demo.follows.filter(f=>f!==ex):demo.follows.concat({id:crypto.randomUUID(),wishId:wish.id,userId:user.id,createdAt:now()}); save(); return;} const fd=await databases.listDocuments(appwriteConfig.databaseId,appwriteConfig.followsTableId,[Query.equal('wish_id',wish.id),Query.equal('user_id',user.id)]); if(fd.documents[0]) await databases.deleteDocument(appwriteConfig.databaseId,appwriteConfig.followsTableId,fd.documents[0].$id); else await databases.createDocument(appwriteConfig.databaseId,appwriteConfig.followsTableId,ID.unique(),{wish_id:wish.id,user_id:user.id,created_at:now()}); },
  async offer(wish:Wish,user:User,offerType:OfferType,message:string,contactUrl?:string,stepId?:string){ const t=now(); if(isDemoMode){ demo.offers.unshift({id:crypto.randomUUID(),wishId:wish.id,stepId,wishOwnerId:wish.ownerId,helperId:user.id,helperName:user.name,offerType,message,contactUrl,status:'offered',createdAt:t,updatedAt:t}); await createUpdate(wish,user,offerType==='idea'?'idea_added':'help_offered',`${user.name} offered: ${message}`); save(); return;} await databases.createDocument(appwriteConfig.databaseId,appwriteConfig.helpTableId,ID.unique(),{wish_id:wish.id,step_id:stepId,wish_owner_id:wish.ownerId,helper_id:user.id,helper_name:user.name,offer_type:offerType,message,contact_url:contactUrl,status:'offered',created_at:t,updated_at:t}); await createUpdate(wish,user,offerType==='idea'?'idea_added':'help_offered',`${user.name} offered: ${message}`); }
};
